spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/comment?serverTimezone=Asia/Shanghai
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver