spring:
  datasource:
    druid:
      url: jdbc:mysql://8.140.235.93:3306/resource?serverTimezone=Asia/Shanghai
      username: root
      password: '021415'
      driver-class-name: com.mysql.cj.jdbc.Driver

# 该配置将会覆盖IpLimitConfig的默认值
gateway:
  ip-limit:
    key: "gateway:ipLimit:"
    count: 30
    time: 5
    ttl: 10
