security:
  config:
    identity-header: user-id
    # 配置需要认证的接口，中间不能加空格
    must-auth-url: /blog-console/**
  # JWT配置
  jwt:
    # 密匙KEY
    key: "xxxx"
    # token在http头中的命名
    header-name: "token"
    # 签名发放者
    issuer: "scblogs.cn"
    # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
    expiration: 604800
