spring:
  datasource:
    druid:
      url: jdbc:mysql://8.140.235.93:3306/blink?serverTimezone=Asia/Shanghai
      username: root
      password: '021415'
      driver-class-name: com.mysql.cj.jdbc.Driver