spring:
  datasource:
    druid:
      url: jdbc:mysql://8.140.235.93:3306/comment?serverTimezone=Asia/Shanghai
      username: root
      password: '021415'
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀