security:
  config:
    identity-header: user-id
    # 配置需要认证的接口
    must-auth-url: /blog-console/**
  # JWT配置
  jwt:
    # 密匙KEY
    key: "design"
    # token在http头中的命名
    header-name: "token"
    # 签名发放者
    issuer: "scblogs.com"
    # 过期时间 单位秒 7天后过期
    expiration: 604800
